services:
  wechat_novnc:
    build:
      context: .
      dockerfile: dockerfile.novnc
    container_name: wechat_novnc
    restart: unless-stopped
    environment:
      AUTOCONNECT: true
      VNC_PASSWORD: xxxxxx
      # 使用 wxbot_linux 容器的名字作为 VNC_SERVER，这样可以直接通过 Docker 的内置 DNS 进行连接
      VNC_SERVER: wxbot_linux:5900
      VIEW_ONLY: false
    # If you are not using nginx, release the comments and comment out the nginx container
    # ports:
    #   - "26080:6080"

    networks:
      - wechat_network

  wxbot_linux:
    build:
      context: .
      dockerfile: dockerfile.wechat
    container_name: wxbot_linux
    restart: unless-stopped
    volumes:
      - ./data:/home/user/xwechat_files
      - ./vncpass:/home/user/wxbot
    networks:
      - wechat_network
  # If you are not using nginx, release the comments and comment out the nginx container
  nginx:
    image: nginx:alpine3.20-slim
    container_name: wxbot_linux_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/.htpasswd
    ports:
      - "80:80"
    networks:
      - wechat_network

networks:
  wechat_network:
    driver: bridge

